POST http://127.0.0.1:5000/trains
Content-Type: application/json


  {
    "name": "CBE Bangalore ",
    "start": "CBE",
    "end": "Bangalore",
    "departure": "02:00 PM",
    "arrival": "08:30 PM",
    "duration": "06h 30m",
    "seats": 95,
    "price": 390
  }



###

GET http://127.0.0.1:5000/trains

###

PUT http://127.0.0.1:5000/trains/6
Content-Type: application/json

{
    "price": 1500,
    "seats": 200
}

###

DELETE http://127.0.0.1:5000/trains/6

###
POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
    "message": "i want to go to cbe"
}

###
DELETE http://127.0.0.1:5000/delete_chat_history
