POST http://127.0.0.1:5000/trains
Content-Type: application/json


[
{
  "name": "Chennai Kovai Express",
  "start": "Chennai",
  "end": "CBE",
  "departure": "07:45 PM",
  "arrival": "04:15 AM",
  "duration": "08h 30m",
  "seats": 82,
  "price": 540
}

]




###

GET http://127.0.0.1:5000/trains

###

PUT http://127.0.0.1:5000/trains/6
Content-Type: application/json

{
    "price": 1500,
    "seats": 200
}

###

DELETE http://127.0.0.1:5000/trains/6

###
POST http://127.0.0.1:5000/chat
Content-Type: application/json

{
    "message": "hi"
}

###
DELETE http://127.0.0.1:5000/delete_chat_history
